"""Generator for the `autonomous_city` world: a small autonomous-operations test facility with
five distinct areas. Deterministic; run `python sim/worlds/autonomous_city.py` to regenerate
sim/worlds/autonomous_city.sdf (the generated file is checked in so Gazebo never needs Python).

Layout (metres, x east, y north):

        y+                     URBAN (NE)                HILL (NW)
   INDUSTRIAL (W)      ┌────────────────────┐        terraces + ramp
   warehouses, tanks,  │ 3x3 blocks, streets │
   containers, fence   └────────────────────┘
        ──────── bridge ────────── main road (E-W, y = -20) ───────────
   OPERATIONS (S centre): pads alpha/bravo/charlie, apron, tower, service bays
                       OPEN FIELD (SE): test track loop, poles, markers
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from assets import (apron, barrier, bridge, building, container_stack, fence, landing_pad, marking, mast_light,  # noqa: E402
                    platform_static, pole, ramp, road, tank, terrace, tower, wall, warehouse)
from assets.palette import material  # noqa: E402

HEADER = """<?xml version="1.0" ?>
<!-- GENERATED by sim/worlds/autonomous_city.py - edit the generator, not this file.
     Physics/plugins, lighting and agents are injected at load time by simapi (markers below). -->
<sdf version="1.9">
  <world name="autonomous_city">
    <!-- @physics -->
    <gravity>0 0 -9.8</gravity>
    <spherical_coordinates>
      <surface_model>EARTH_WGS84</surface_model><world_frame_orientation>ENU</world_frame_orientation>
      <latitude_deg>47.3977</latitude_deg><longitude_deg>8.5456</longitude_deg><elevation>488.0</elevation><heading_deg>0</heading_deg>
    </spherical_coordinates>
    <!-- @lighting -->
"""
FOOTER = """
    <!-- @agents -->
  </world>
</sdf>
"""


def ground() -> str:
    return f"""
    <model name="ground"><static>true</static><link name="link">
      <collision name="collision"><geometry><plane><normal>0 0 1</normal><size>600 600</size></plane></geometry>
        <surface><friction><ode><mu>100</mu><mu2>50</mu2></ode></friction></surface></collision>
      <visual name="visual"><geometry><plane><normal>0 0 1</normal><size>600 600</size></plane></geometry>{material("ground")}</visual>
    </link></model>"""


def operations_area() -> list[str]:
    m = []
    m.append(apron("ops_apron", 0, -55, 90, 40))
    m.append(landing_pad("pad_alpha", -25, -55, 5.0))
    m.append(landing_pad("pad_bravo", 0, -55, 5.0))
    m.append(landing_pad("pad_charlie", 25, -55, 5.0))
    m.append(tower("ops_tower", 45, -70, 28))
    for i, x in enumerate((-38, -26, -14)):
        m.append(building(f"service_bay_{i + 1:02d}", x, -82, 10, 8, 5, style="steel", bands=False))
    m.append(marking("launch_zone", 0, -35, 60, 3.0, color="accent2"))
    for i, x in enumerate((-45, 45)):
        m.append(mast_light(f"ops_mast_{i + 1:02d}", x, -40))
    m.append(wall("ops_wall_s", 0, -95, 100, 2.5))
    for i, x in enumerate((-30, -10, 10, 30)):
        m.append(barrier(f"ops_barrier_{i + 1:02d}", x, -36, 3.0))
    return m


def urban_area() -> list[str]:
    m = []
    heights = [[14, 22, 10], [30, 12, 18], [16, 26, 12]]
    for r in range(3):
        for c in range(3):
            x, y = 30 + c * 26, 15 + r * 26
            h = heights[r][c]
            m.append(building(f"building_{r * 3 + c + 1:02d}", x, y, 14, 14, h, helipad=(h == 30)))
    m.append(road("street_ns_1", 43, 41, 90, yaw=1.5708, width=8))
    m.append(road("street_ns_2", 69, 41, 90, yaw=1.5708, width=8))
    m.append(road("street_ew_1", 56, 28, 80, width=8))
    m.append(road("street_ew_2", 56, 54, 80, width=8))
    m.append(wall("courtyard_wall", 56, 2, 60, 3.0))
    m.append(marking("plaza", 56, -8, 40, 14, color="apron"))
    for i, (x, y) in enumerate(((36, -8), (76, -8))):
        m.append(pole(f"plaza_pole_{i + 1:02d}", x, y, 6))
    return m


def industrial_area() -> list[str]:
    m = []
    m.append(warehouse("warehouse_01", -70, 20, 40, 18, 9))
    m.append(warehouse("warehouse_02", -70, 50, 40, 18, 11))
    m.append(warehouse("warehouse_03", -20, 35, 24, 14, 8, yaw=1.5708))
    m.append(tank("tank_01", -95, 75, 4.5, 9))
    m.append(tank("tank_02", -83, 75, 4.5, 9))
    m.append(tower("chimney_01", -105, 30, 34, r=1.2, cabin=False))
    for i, (x, y, yaw) in enumerate(((-45, 8, 0), (-52, 12, 0.4), (-38, 14, -0.3))):
        m.append(container_stack(f"containers_{i + 1:02d}", x, y, yaw))
    m.append(fence("restricted_fence_n", -90, 95, 60))
    m.append(fence("restricted_fence_w", -120, 65, 60, yaw=1.5708))
    m.append(fence("restricted_fence_s", -90, 35, 60))
    m.append(marking("restricted_zone", -90, 65, 56, 56, color="accent"))
    m.append(road("industrial_road", -60, -5, 120, width=8))
    m.append(mast_light("ind_mast_01", -60, 65, 14))
    return m


def open_area() -> list[str]:
    m = []
    m.append(road("track_s", 90, -90, 100, width=7))
    m.append(road("track_n", 90, -50, 100, width=7))
    m.append(road("track_w", 40, -70, 40, yaw=1.5708, width=7))
    m.append(road("track_e", 140, -70, 40, yaw=1.5708, width=7))
    for i, (x, y) in enumerate(((60, -70), (90, -70), (120, -70))):
        m.append(pole(f"field_pole_{i + 1:02d}", x, y, 8))
    m.append(marking("field_grid", 90, -70, 60, 12, color="marking"))
    m.append(platform_static("field_platform", 130, -110, 10, 10, 6))
    return m


def elevated_and_terrain() -> list[str]:
    m = []
    m.append(bridge("bridge_01", 0, -20, 44, 9, width=8))
    m.append(road("main_road_w", -90, -20, 130, width=10))
    m.append(road("main_road_e", 90, -20, 130, width=10))
    m.append(terrace("hill_01", -60, 120, radii=(34, 25, 16), step=3.5))
    m.append(ramp("hill_ramp", -60, 76, 24, 8, 3.5))
    m.append(ramp("embankment_01", 90, -125, 30, 60, 4.0, yaw=1.5708))
    m.append(platform_static("sky_platform", 110, 50, 12, 12, 18))
    m.append(tower("relay_tower", 120, 90, 40, r=1.4))
    return m


def build() -> str:
    parts = [ground()]
    for area in (operations_area(), urban_area(), industrial_area(), open_area(), elevated_and_terrain()):
        parts += area
    return HEADER + "".join(parts) + FOOTER


if __name__ == "__main__":
    out = Path(__file__).with_suffix(".sdf")
    out.write_text(build())
    print(f"wrote {out} ({out.stat().st_size // 1024} kB, {build().count('<model name=')} models)")
